name: ci 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying the pages website
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      deployments: read
      packages: none
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
